services:
  - type: web
    name: smarthire
    env: python
    plan: free
    # We are adding a semi-colon to chain the commands: install dependencies AND download the model
    buildCommand: pip install -r requirements.txt; python -m spacy download en_core_web_sm
    startCommand: gunicorn app:app